// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ricart/ricart.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_ricart_ricart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ricart_ricart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_ricart_ricart_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RequestMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReplyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_ricart_ricart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ricart_ricart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_ricart_ricart_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ricart_ricart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ricart_ricart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ricart_ricart_proto_rawDescGZIP(), []int{2}
}

var File_ricart_ricart_proto protoreflect.FileDescriptor

const file_ricart_ricart_proto_rawDesc = "" +
	"\n" +
	"\x13ricart/ricart.proto\x12\x06ricart\"G\n" +
	"\x0eRequestMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"'\n" +
	"\fReplyMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\"\a\n" +
	"\x05Empty2w\n" +
	"\rRicartService\x124\n" +
	"\vSendRequest\x12\x16.ricart.RequestMessage\x1a\r.ricart.Empty\x120\n" +
	"\tSendReply\x12\x14.ricart.ReplyMessage\x1a\r.ricart.EmptyB\x1aZ\x18ricart/proto/proto;protob\x06proto3"

var (
	file_ricart_ricart_proto_rawDescOnce sync.Once
	file_ricart_ricart_proto_rawDescData []byte
)

func file_ricart_ricart_proto_rawDescGZIP() []byte {
	file_ricart_ricart_proto_rawDescOnce.Do(func() {
		file_ricart_ricart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ricart_ricart_proto_rawDesc), len(file_ricart_ricart_proto_rawDesc)))
	})
	return file_ricart_ricart_proto_rawDescData
}

var file_ricart_ricart_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ricart_ricart_proto_goTypes = []any{
	(*RequestMessage)(nil), // 0: ricart.RequestMessage
	(*ReplyMessage)(nil),   // 1: ricart.ReplyMessage
	(*Empty)(nil),          // 2: ricart.Empty
}
var file_ricart_ricart_proto_depIdxs = []int32{
	0, // 0: ricart.RicartService.SendRequest:input_type -> ricart.RequestMessage
	1, // 1: ricart.RicartService.SendReply:input_type -> ricart.ReplyMessage
	2, // 2: ricart.RicartService.SendRequest:output_type -> ricart.Empty
	2, // 3: ricart.RicartService.SendReply:output_type -> ricart.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ricart_ricart_proto_init() }
func file_ricart_ricart_proto_init() {
	if File_ricart_ricart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ricart_ricart_proto_rawDesc), len(file_ricart_ricart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ricart_ricart_proto_goTypes,
		DependencyIndexes: file_ricart_ricart_proto_depIdxs,
		MessageInfos:      file_ricart_ricart_proto_msgTypes,
	}.Build()
	File_ricart_ricart_proto = out.File
	file_ricart_ricart_proto_goTypes = nil
	file_ricart_ricart_proto_depIdxs = nil
}
