// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: ricart/ricart.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RicartService_SendRequest_FullMethodName = "/ricart.RicartService/SendRequest"
	RicartService_SendReply_FullMethodName   = "/ricart.RicartService/SendReply"
)

// RicartServiceClient is the client API for RicartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartServiceClient interface {
	SendRequest(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Empty, error)
	SendReply(ctx context.Context, in *ReplyMessage, opts ...grpc.CallOption) (*Empty, error)
}

type ricartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartServiceClient(cc grpc.ClientConnInterface) RicartServiceClient {
	return &ricartServiceClient{cc}
}

func (c *ricartServiceClient) SendRequest(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RicartService_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricartServiceClient) SendReply(ctx context.Context, in *ReplyMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RicartService_SendReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartServiceServer is the server API for RicartService service.
// All implementations must embed UnimplementedRicartServiceServer
// for forward compatibility.
type RicartServiceServer interface {
	SendRequest(context.Context, *RequestMessage) (*Empty, error)
	SendReply(context.Context, *ReplyMessage) (*Empty, error)
	mustEmbedUnimplementedRicartServiceServer()
}

// UnimplementedRicartServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartServiceServer struct{}

func (UnimplementedRicartServiceServer) SendRequest(context.Context, *RequestMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedRicartServiceServer) SendReply(context.Context, *ReplyMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReply not implemented")
}
func (UnimplementedRicartServiceServer) mustEmbedUnimplementedRicartServiceServer() {}
func (UnimplementedRicartServiceServer) testEmbeddedByValue()                       {}

// UnsafeRicartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartServiceServer will
// result in compilation errors.
type UnsafeRicartServiceServer interface {
	mustEmbedUnimplementedRicartServiceServer()
}

func RegisterRicartServiceServer(s grpc.ServiceRegistrar, srv RicartServiceServer) {
	// If the following call pancis, it indicates UnimplementedRicartServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RicartService_ServiceDesc, srv)
}

func _RicartService_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartServiceServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartService_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartServiceServer).SendRequest(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _RicartService_SendReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartServiceServer).SendReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartService_SendReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartServiceServer).SendReply(ctx, req.(*ReplyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RicartService_ServiceDesc is the grpc.ServiceDesc for RicartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ricart.RicartService",
	HandlerType: (*RicartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _RicartService_SendRequest_Handler,
		},
		{
			MethodName: "SendReply",
			Handler:    _RicartService_SendReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ricart/ricart.proto",
}
